version: 1.1.0.{build}

assembly_info:
  patch: true
  file: GlobalAssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

install:
- cmd: git submodule update --init --recursive

configuration: Release
platform: Any CPU

before_build:
- cmd: >-
    dotnet restore

    nuget restore Luxa4Slack.Tray\packages.config -PackagesDirectory packages

build:
  project: Luxa4Slack.sln
  verbosity: minimal

after_build:
- cmd: >-
    del /Q Luxa4Slack.Tray\bin\Release\*.xml

    del /Q Luxa4Slack.Tray\bin\Release\*.pdb

    7z a Luxa4Slack-Tray-%APPVEYOR_BUILD_VERSION%.zip %CD%\Luxa4Slack.Tray\bin\Release\*

    dotnet publish Luxa4Slack.Console --configuration Release --framework netcoreapp1.0

    del /Q Luxa4Slack.Console\bin\Release\netcoreapp1.0\*.pdb

    del /Q Luxa4Slack.Console\bin\Release\netcoreapp1.0\publish\*.pdb

    7z a Luxa4Slack-Console-%APPVEYOR_BUILD_VERSION%.zip %CD%\Luxa4Slack.Console\bin\Release\netcoreapp1.0\*

artifacts:
- path: Luxa4Slack-Tray-*.zip
  name: Luxa4Slack-Tray
- path: Luxa4Slack-Console-*.zip
  name: Luxa4Slack-Console

deploy:
- provider: GitHub
  auth_token:
    secure: fUfvn0AxoiLyyw4vz+0XESvl/FibBKHSfQwAYquPQqI9AwHhoPd4qNZonfjvLTuf
  artifact: Luxa4Slack
  draft: true
  on:
    branch: master
    appveyor_repo_tag: true
